/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the.avengers.hospitalscheduler.primitives;

import java.time.DayOfWeek;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;

/**
 * A Day contains the time slots and the arrivals for that particular day.
 *
 * @author Tony Stark
 */
public class Day {

    /**
     * The time slots for a particular day, either 16 or 32 are available
     * depending on which day of the week it is.
     */
    public TimeSlot[] timeSlots;

    /**
     * The arrivals variable stores the arrivals the day. This is generated by
     * the arrival factory.
     */
    public Arrival[] arrivals;

    /**
     * The daily overtime can be calculated by calculating the difference
     * between the scan end time of the last patient on a particular day and the
     * session end time of the day.
     *
     * @return the amount of overtime of a day.
     */
    public Duration tOverTime() {
        TimeSlot lastTS = this.timeSlots[this.timeSlots.length - 1];
        Arrival lastArrival = this.arrivals[this.arrivals.length - 1];

        Duration overTime = Duration.between(lastTS.tEnd(), lastArrival.tScan);
        if (overTime.isNegative()) {
            return Duration.ZERO;
        } else {
            return overTime;
        }
    }

}
